### ISSUE TITLE
Scroll to zoom not sensitive enough on Firefox

### ISSUE THREAD

**Issue by kasbah** [tracespace/viewer#10]
The scroll to zoom of the render view is waaaaay not sensitive enough on Firefox (47, Ubuntu 14.04).

**Comment by mcous** [comment]
Pan zoom needs a lot of work in general. I think this one might be due to the fact that I tuned it in OSX with system-level inertial scrolling turned on. If I turn inertial-scrolling off, it's a lot slower. But slow zoom isn't isolated to Firefox in that instance.

Will try this out on my Ubuntu machine. Not sure what a solution would be yet

**Comment by kasbah** [comment]
It seems fine on Chrome though. Doesn't really work at all on Firefox.
