### ISSUE TITLE
Layers pane doesn't scroll on Firefox

### ISSUE THREAD

**Issue by kasbah** [tracespace/viewer#3]
This is what it looks like on Firefox 47 on Ubuntu 14.04. Works fine in Chrome. 

No errors on console (but debug state is being printed). 

![noscroll](https://cloud.githubusercontent.com/assets/206854/17121542/62ffb036-52cc-11e6-99c8-ef7d90ebf3a0.png)

**Comment by mcous** [comment]
Womp. I'm pretty sure I'm using some flexbox hackery on that, and given I don't really know flexbox (and I also probably did it at like 3 in the morning), that may have been a bold move™

At one point it was working ok by using a combination of heights, max-heights, and pointer-event: none's, but (because of the pointer-event stuff) I didn't like the solution. Probably need to spend some time Googling. Any ideas?

**Comment by kasbah** [comment]
Not really, setting `overflow: scroll` on any of the surrounding elements doesn't seem to help. 

Edit: The about pane does scroll properly.
