### ISSUE TITLE
Should be able to download all the files in a zip

### ISSUE THREAD

**Issue by mcous** [tracespace/viewer#9]
The user should be able to zip up all SVGs of the current layers / boards (or, in the case of #7, whichever board is open) and download that zip. The zipping should be done in the worker thread, which is fine considering all the gerber files are cached there and they'll need to be re-rendered, anyway.

Will probably use
- https://stuk.github.io/jszip/
- https://github.com/eligrey/FileSaver.js

**Comment by mundodisco8** [comment]
I read on #16 that you don't have much free time to work on this feature, but I would like to make ask for a feature, in case you do and it's easy to implement. When I export svgs, normally the copper-filled planes are exported as an outline, plus as many lines of a certain thickness (the thickness you specified for your polygon) as required to cover them, instead of a polygon with infill. I get the reason why it is exported that way, but it would be so much nicer if we get a simple polygon, as that is much easier to work with (for example, to export to your CAD program).

Thanks!

**Comment by mcous** [comment]
Hey! Thanks for the note! Unfortunately, that many-lines-instead-of-a-fill (stroked fill) is because of the CAD program. From my own experience and hearsay, KiCad will output polygon fills, Eagle will output stroke fills, Altium can do both I think depending on the settings (?), PADS will do strokes, etc.

Since this tool only works by translating Gerber files to SVG (i.e. no real geometry calculations, just vector language to other vector language), switching stroked fills to region fills would be really really hard™ for tracespace.

**Comment by mundodisco8** [comment]
Hi,

Thanks for your quick response. It seems that you had already investigated the issue! 

Well, then it means I will have to do a lot of cleaning :( 
Thanks anyway!
